# Generated by Django 3.2 on 2023-03-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customerfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerfeedback",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Products/Product Range", "Products/Product Range"),
                    ("Order/Payment", "Order/Payment"),
                    ("Store Structure/Design", "Store Structure/Design"),
                    (
                        "General Improvement Suggestions",
                        "General Improvement Suggestions",
                    ),
                    ("Other", "Other"),
                ],
                default="General Improvement Suggestions",
                max_length=31,
            ),
        ),
    ]
