# Generated by Django 3.2 on 2023-05-08 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_auto_20230508_1325"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="return",
            name="action",
        ),
        migrations.RemoveField(
            model_name="return",
            name="reason",
        ),
    ]
