# Generated by Django 3.2 on 2023-05-08 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('The goods are damaged', 'The goods are damaged'), ('The wrong goods were delivered', 'The wrong goods were delivered'), ('You do not like the goods (anymore)', 'You do not like the goods (anymore)'), ('Other', 'Other')], default='The goods are damaged', max_length=35),
        ),
    ]
