# Generated by Django 3.2 on 2023-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_return_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='order',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='return',
            name='products',
            field=models.CharField(max_length=150),
        ),
    ]
