# Generated by Django 3.2 on 2023-02-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0004_rename_has_quantity_product_has_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=32),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "order_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8
                    ),
                ),
                (
                    "delivery_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8
                    ),
                ),
                ("email_address", models.EmailField(max_length=75)),
                ("full_name", models.CharField(max_length=50)),
                ("delivery_address1", models.CharField(max_length=100)),
                (
                    "delivery_address2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("state", models.CharField(max_length=100, null=True)),
                ("country", models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "product_weight",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "lineitem_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=6
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderlineitems",
                        to="checkout.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
