# Generated by Django 3.2 on 2023-02-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_auto_20230216_1411"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="town_or_city",
            field=models.CharField(default="", max_length=80),
        ),
    ]
