# Generated by Django 3.2 on 2023-02-16 14:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0003_alter_order_town_or_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, null=True
            ),
        ),
    ]
