# Generated by Django 3.2 on 2023-02-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230131_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_quantity',
            new_name='has_weight',
        ),
    ]
