# Generated by Django 3.2 on 2023-03-13 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0008_alter_productreview_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_review",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
