# Generated by Django 3.2 on 2023-03-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_auto_20230313_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6
            ),
        ),
    ]
