# Generated by Django 3.2 on 2023-03-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_arrived',
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
